const classes = {
    appCompleteBox: "appCompleteBox",
    appIncompleteBox: "appIncompleteBox",
    app: {
        incompleteApplication: "app-incomplete",
        completeApplication: "app-complete",
        confirmed: "app-confirmed",
        admitted: "app-admitted",
        declined: "app-declined",
        rejected: "app-rejected",
    },
    avatar: "avatar",
    descriptionText: "descriptionText",
    errorText: "error",
    homeContainer: "homeContainer",
    loginContainer: "loginContainer",
    loginMsg: "loginMsg",
    logo: "logo",
    material: "material",
    modalContainer: "modalContainer",
    paper: "paper",
    register: "register",
    resendVerification: "resendVerification",
    submit: "submit",
    successText: "success_text",
    toolbarButtons: "toolbarButtons",
    textLink: "textLink",
    unverifiedBox: "unverifiedBox",
};

export default classes;
