export const userProfileDefault = {
    confirmation: {
        discord: "",
        pNum: "",
    },
    status: {
        admitted: false,
        checkedIn: false,
        completeProfile: false,
        confirmed: false,
        declined: false,
        isMentor: false,
        reimbursmentGiven: false,
        rejected: false,
        timestampAdmitted: "",
    },
};

export const fields = [
    {
        type: "String",
        titleLabel: "What is your name?",
        order: 1,
        required: true,
        keyRef: "name",
    },
    {
        type: "String",
        titleLabel: "What school do you go to?",
        order: 2,
        required: true,
        keyRef: "school",
    },
    {
        required: true,
        titleLabel: "What is your program name?",
        order: 3,
        type: "String",
        keyRef: "program",
    },
    {
        order: 4,
        required: true,
        titleLabel: "What is your year of study?",
        type: "number",
        keyRef: "studyLevel",
    },
    {
        type: "number",
        order: 5,
        required: true,
        titleLabel: "What is your age?",
        keyRef: "age",
    },
    {
        required: true,
        order: 6,
        type: "String",
        titleLabel: "What country are you from?",
        keyRef: "country",
    },
    {
        titleLabel: "What city are you from?",
        type: "String",
        required: false,
        order: 7,
        keyRef: "city",
    },
    {
        order: 8,
        requred: true,
        type: "String",
        titleLabel: "Describe yourself",
        keyRef: "description",
    },
    {
        titleLabel: "Etnhicity",
        type: "String",
        order: 9,
        required: true,
        keyRef: "ethnicity",
    },
    {
        order: 10,
        type: "String",
        required: true,
        titleLabel: "exp?",
        keyRef: "exp",
    },
    {
        titleLabel: "Gender",
        options: ["Male", "Female", "Non-binary", "Prefer not to answer"],
        required: true,
        type: "dropdown",
        order: 11,
        keyRef: "gender",
    },
    {
        titleLabel: "When will you graduate?",
        order: 12,
        required: true,
        type: "number",
        keyRef: "gradYear",
    },
    {
        titleLabel: "How many hackathons have you attended",
        type: "number",
        required: true,
        order: 13,
        keyRef: "hackNum",
    },
    {
        order: 14,
        type: "String",
        titleLabel: "How did you hear about us?",
        required: true,
        keyRef: "hearAbout",
    },
    {
        titleLabel: "Do you agree to MLH terms?",
        type: "Boolean",
        order: 15,
        required: true,
        keyRef: "mlhAuth",
    },
];

export const fieldKeys = fields.map((field) => field.keyRef);
