export const fields = [
    {
        type: "String",
        titleLabel: "What is your full name? Ex. John Smith",
        order: 1,
        required: true,
        keyRef: "name",
    },
    {
        titleLabel: "Are you currently in high-school?",
        type: "dropdown",
        options: ["Yes", "No"],
        required: false,
        order: 2,
        keyRef: "highschoolHacker",
    },
    {
        type: "String",
        titleLabel: "What university / high-school do you currently attend?",
        order: 2,
        required: true,
        keyRef: "school",
    },
    {
        required: true,
        titleLabel:
            "What program are you currently in? Please put N/A if you are in high-school.",
        order: 3,
        type: "String",
        keyRef: "program",
    },
    {
        order: 4,
        required: true,
        titleLabel: "What is your year of study? Ex. 3rd Year",
        type: "Integer",
        keyRef: "studyLevel",
        limit: [1, 100],
    },
    {
        type: "Integer",
        order: 5,
        required: true,
        titleLabel: "What is your age?",
        keyRef: "age",
        limit: [12, 100],
    },
    {
        required: true,
        order: 6,
        type: "String",
        titleLabel:
            "What country will you be in during RU Hacks 2021 (May 2nd - April 1st)?",
        keyRef: "country",
    },
    {
        titleLabel: "What city will you be in during RU Hacks 2021?",
        type: "String",
        required: false,
        order: 7,
        keyRef: "city",
    },
    {
        titleLabel: "What is your race/ethnicity?",
        options: [
            "American Indian or Alaskan Native",
            "Asian/pacific Islander",
            "Black or African American",
            "Hispanic",
            "White / Caucasian",
            "Multiple ethnicity / Other (Please specify)",
            "Prefer not to answer",
        ],
        type: "dropdown",
        order: 8,
        required: true,
        keyRef: "ethnicity",
    },
    {
        order: 9,
        type: "String",
        required: false,
        titleLabel:
            "If selected other or Multiple ethnicity please specify here",
        keyRef: "ethnicityOther",
    },
    {
        order: 10,
        requred: true,
        type: "String",
        titleLabel: "What is a project you are proud to have worked on?",
        keyRef: "description",
        charLimit: 1000,
    },
    {
        order: 11,
        type: "String",
        required: true,
        titleLabel:
            "What is your experience with programming? What languages/frameworks are you familiar with, if any?",
        keyRef: "exp",
    },
    {
        titleLabel: "Personal Pronouns",
        options: [
            "He/Him",
            "She/Her",
            "They/Them",
            "Prefer not to answer",
            "Other (please specify)",
        ],
        required: true,
        type: "dropdown",
        order: 12,
        keyRef: "pronouns",
    },
    {
        order: 13,
        type: "String",
        required: false,
        titleLabel: "If selected other please specify here",
        keyRef: "otherGender",
    },
    {
        titleLabel: "What year will you be graduating?",
        order: 14,
        required: true,
        type: "Integer",
        keyRef: "gradYear",
        limit: [2021, 3000000],
    },
    {
        titleLabel: "How many hackathons have you attended in the past?",
        type: "Integer",
        required: true,
        order: 15,
        keyRef: "hackNum",
        limit: [1, 10000],
    },
    {
        titleLabel:
            "Would you potentially be interested in participating in a Hardware-based category hack?",
        type: "Boolean",
        required: false,
        order: 16,
        keyRef: "hardwareHack",
    },
    {
        order: 17,
        type: "String",
        titleLabel: "How did you hear about us?",
        required: true,
        keyRef: "hearAbout",
    },
    {
        order: 18,
        type: "String",
        titleLabel: "What is your favorite flavour of yogurt?",
        required: false,
        keyRef: "yogurt",
    },
    {
        titleLabel: "Do you agree to the ",
        staticLinkText: "MLH Code of Conduct?",
        link: "https://static.mlh.io/docs/mlh-code-of-conduct.pdf",
        type: "Boolean",
        order: 19,
        required: true,
        keyRef: "mlhAuth",
    },
];
export const fieldKeys = fields.map((field) => field.keyRef);

export const profileUpdateObject = (updatedAt) => ({
    updatedAt,
});
